imports:
    - { resource: config_dev.yml }

services:
    Tests\VcrGuzzleMiddleware: ~
    wizaplace.guzzle.decorating_handler2:
        factory: 'GuzzleHttp\HandlerStack::create'
        class: 'GuzzleHttp\HandlerStack'
        decorates: 'wizaplace.guzzle.handler'
        arguments: ['@wizaplace.guzzle.decorating_handler.inner']
        calls:
            - ['push', ['@Tests\VcrGuzzleMiddleware']]
